### ISSUE TITLE
++ kadi upload

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#10]
@Hezel2000 wie genau soll/en die Datei/en formatiert sein, die auf Kadi hochgeladen werden sollen? (über "Data Export & Upload")

**Comment by Hezel2000** [comment]
Geht es um die bearbeiteten files? Am Besten wäre da wohl eine kombinierte Excel-Tabelle mit entsprechenden Tabellenblättern. Da das ja prozessierte Dateien sind, die also jederzeit neu generiert werden können, muss das mE nicht unbedingt csv sein. Ist evtl. auch etwas 'nutzerfreundlicher'.

**Comment by MaraHochstein** [comment]
Ich weiß nicht, was ihr gerne auf Kadi wieder hochgeladen haben wollt. Aber ja, es ginge um die zusammengeführten Daten. Die csv, die man sich exportieren kann, könnte ich theoretisch nehmen, sie hat mehrere Blätter. Ansonsten müsstest Du mir mal eine genaue Liste machen, wie die Files aufgebaut werden sollen & benannt werden sollen. Ich weiß nicht, in wie fern ihr die Datei später wiederverwendet.

**Comment by Hezel2000** [comment]
Es werden vermutlich genau die csv sein, damit man die nicht noch mal produzieren muss, sondern das nächste Mal direkt herunter laden kann.
Das könnte auch später noch angepasst werden.

**Comment by MaraHochstein** [comment]
soll das Hochladen nur dafür sein, damit man hinterher nochmal die Einstellungen wiederherstellen kann? Oder soll es für weitere Arbeit dann auf Kadi hochgeladen werden, damit man ggf später nochmal von Kadi runterladen kann?

Denn falls es ersteres ist, dann würde ich es nicht als diese user-formatierte csv hochladen, sondern die session-state-variablen in eine json o.ä., denn sonst müsste ich hinterher die csv wieder umständlicher auslesen.

Soll der upload noch fertig werden bis Do?

**Comment by Hezel2000** [comment]
Im Grunde würden die session_state Parameter genügen. Primär geht es darum, dass man nicht jedes Mal die gesamte clean-up Prozedur durchlaufen muss. Es könnte dann einfach angezeigt werden, ob ein clean-up schon mal durchgeführt wurde, und ob man das anwenden will. Dann könnte man sogar verschiedene clean-ups speichern …

Am Do wirst Du für Deinen Teil ca. 10 Min Zeit haben. Wenn da noch was fehlt, wäre das sicher kein Problem.
Cool wäre natürlich einen v1 für eine mögliche Publikation.
Unser MAPS-Artikel ist weiterhin under review, ich habe eben mal nach gesehen. Sind ja auch ganze füllige 8 Seiten ...

**Comment by MaraHochstein** [comment]
Meinst Du mit "clean-up" die Filtereinstellungen aus dem zweiten step? Wenn ja, dann würde ich nicht den session_state an sich komplett speichern (das wäre zt unsinnig bzw doppelt gemoppelt, da ich die Datei selbst ja dennoch von kadi ziehen und aufsplitten muss.. das ist nicht wirklich sparsamer, als die Originaldaten zu laden und zu prozessieren, hinzu kommt der zusätzliche code für die fast gleiche Aufgabe), sondern nur die Filtereinstellungen.

Falls man theoretisch eine Datei updaten würde, könnte dies mit berücksichtigt werden (falls z.B. irgendwo ein Tippfehler im Projektnamen o.ä. auffällt, den man in der Originaldatei ändert) und dann die korrekten Rohdaten mit den vorher genutzten Filtereinstellungen geladen werden.

Zudem könnte man so einfach Filtereinstellungen auf kadi selbst kopieren und für ein anderen record anwenden (z.B. gibt es eine Messreihe, die zusammen gehört, wo überall die gleichen Filter angewandt werden sollen)

**Comment by Hezel2000** [comment]
Ich glaube, dazu müsste ich das dann doch mal sehen. Insgesamt geht es in die Richtung, ganz genau kann ich das nicht beantworten.

**Comment by MaraHochstein** [comment]
@Hezel2000 Sollen die guest-user auch (wenn sie das richtige pw haben) ihre Filtereinstellungen auf den record hochladen können?

**Comment by Hezel2000** [comment]
Ja, eigentlich gerade die, da die ja auch ein ander Mal wieder auf ihren record zugreifen wollen.

**Comment by MaraHochstein** [comment]
- [x] upload filter to kadi from normal login
- [ ] upload filter for guf group

**Comment by MaraHochstein** [comment]
@Hezel2000 ich erhalte einen 403 Error beim Hochladen über die Gruppe (insufficient permissions for this user). Ich habe mir die Rollenbeschreibungen bei Kadi durchgelesen, die Guf-Gruppe ist als Member eingetragen, müsste aber wahrscheinlich als Editor eingetragen werden. Den normalen filter-upload habe ich über dhezel getestet, das funktionierte dort wahrscheinlich direkt, weil der Account Admin ist. Ich weiß nicht genau, wie man das am intelligentesten bei Kadi einstellt, ohne dass man das in jedem record editieren muss. Vielleicht kannst Du die Rolle schneller umstellen?

Anbei der Screenshot wegen der Rollenbeschreibungen
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/06d00c67-6fe5-494c-953f-3e2de7abb139)

**Comment by Hezel2000** [comment]
Ich habe die Permissions der Demo Datasets zum Testen mal auf Editor gesetzt. Das bei allen zu ändern wäre nicht das Riesending, und zukünftig mache ich das gleich, wenn ich die Permissions verteile.

**Comment by MaraHochstein** [comment]
> PS: ich teste aktuell immer mit dem record ....411-ryo

Es macht ja kein Sinn, das jetzt bei den maps einzustellen, wenn dann eher bei verschiedenen anderen. Aber das kann ich ja dann auch machen

**Comment by MaraHochstein** [comment]
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/75ad5c6b-70a9-4893-a62e-d9b199492ae1)

**Comment by Hezel2000** [comment]
Klar, war ja nur zum Testen. Soll ich das bei den anderen noch umstellen?

**Comment by MaraHochstein** [comment]
Ja, sonst kann man den upload nur von Deinem Account aus machen. Ich würde es überall ändern, außer bei den test-records, die sollten eigentlich nur von Admin geändert werden können.

**Comment by Hezel2000** [comment]
Es ist nun in allen Records auf Editor umgestellt (wenn ich mich nichts verklingt habe) und die Demo-Accounts wieder auf Member umgestellt.
