### ISSUE TITLE
[--] calendar for guf records?

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#12]
@Hezel2000 Du meintest mal, die records sollten irgendwie als Kalender dargestellt werden? An welcher Stelle und wofür bräuchtest Du das?

**Comment by Hezel2000** [comment]
Ein Kalender könnte unterschiedliche Funktionen erfüllen. Zum einen, um die Maschine zu buchen – dafür habe ich derzeit einen anderen Kalender, aber alles zentral wäre natürlich schicker. Damit könnten dann evtl. die Records verbunden werden. Aber auch das wäre etwas, das man dann einmal konkret anschauen müsste.

**Comment by MaraHochstein** [comment]
Wie würdest Du Dir die "Verbindung" der Records vorstellen? Wenn es ein klickbarer Kalender ist, dann wäre es von der Bedienung nerviger, sich nach mehreren Monaten / Jahren zu dem Datum zu klicken, anstatt nach dem passenden Namen zu schauen, oder hattest Du an eine andere Darstellung gedacht? Ich finde diese Kalender zum Auswählen immer ungeeignet, wenn das Datum länger her ist. Zudem muss man sich dann das Datum merken oder nachschauen - die Namen sind so wie ich gesehen habe ja immer nach Vor- und Nachnamen der Personen gemacht, da findet man schneller sein Kürzel.

**Comment by Hezel2000** [comment]
Hi Mara,

Da stimme ich Dir zu. Der Kalender wäre weniger für die Record-Suche, sondern vielmehr für die Buchungen. Die records selbst sollen schon über Nutzer-Namen, bzw. deren Collections gefunden werden. Sonst denke ich auch, wird das nichts.
Ich habe aber einen Kalender für Buchungen, das ist also nichts eiliges. Es wäre nur praktisch irgendwann alles an einem Ort zu haben.

 Besten Gruß,  Dominik

**Comment by MaraHochstein** [comment]
Hast Du den Buchungskalender auch über streamlit gemacht? Wenn nicht, was dachtest Du, wie die „Buchung“ gemacht werden soll - eMail notification oder über kadi irgendwie oder …?Am 24.06.2024 um 21:33 schrieb Hezel2000 ***@***.***>:﻿
Hi Mara,



Da stimme ich Dir zu. Der Kalender wäre weniger für die Record-Suche, sondern vielmehr für die Buchungen. Die records selbst sollen schon über Nutzer-Namen, bzw. deren Collections gefunden werden. Sonst denke ich auch, wird das nichts.

Ich habe aber einen Kalender für Buchungen, das ist also nichts eiliges. Es wäre nur praktisch irgendwann alles an einem Ort zu haben.



 Besten Gruß,  Dominik

**Comment by Hezel2000** [comment]
Eintragungen in den Kalender können nur von mir oder einem Hiwi durchgeführt werden. Für alle anderen soll er einfach nur einsehrbar sein, mehr nicht. Wenn Leute sich selbst eintragen könnten, fangen die an sich wild ein- und auszutragen, das funktioniert oftmals nur bedingt gut.

**Comment by MaraHochstein** [comment]
Ja, aber wie soll die „Datenbank“ dahinter verknüpft sein - google calendar oder hast Du da schon was auf streamlit? Du meintest ja, die Funktion besteht schon irgendwo anders. Mit „buchen“ hatte ich auch nicht an selbst eintragen gedacht, sondern an ein Formular mit Wunschtermin o.ä., die Du / Hiwi dann auswerten..Am 28.06.2024 um 12:35 schrieb Hezel2000 ***@***.***>:﻿
Eintragungen in den Kalender können nur von mir oder einem Hiwi durchgeführt werden. Für alle anderen soll er einfach nur einsehrbar sein, mehr nicht. Wenn Leute sich selbst eintragen könnten, fangen die an sich wild ein- und auszutragen, das funktioniert oftmals nur bedingt gut.

**Comment by MaraHochstein** [comment]
@Hezel2000 hier brauche ich noch Info s.o.

**Comment by Hezel2000** [comment]
Das bisherige System ist ein Uni-interner Calendar. Auf den kann per Link zugegriffen werden. Würde das reichen? Der Link wäre:
https://olat-ce.server.uni-frankfurt.de/olat/ical/group/hezel/3Bvi2F/10632003584.ics
Wenn das zu kompliziert ist – das ist nicht die wichtigste Funktion.

**Comment by MaraHochstein** [comment]
@Hezel2000 Ich könnte den Kalender über python sicher darstellen, aber wie genau stellst Du Dir die "Reservierung"/"Anfrage" vor? Wohin sollen die Daten gespeichert werden?

**Comment by Hezel2000** [comment]
Ich bin gerade dabei über unser Justitiariat heraus zu finden, ob ich irgendein DSVGO o.ä. konforme Einverständniserklärung  Nutzer*innen brauche, um deren Namen in den Metadaten aufzunehmen. Das würde natürlich auch für den Kalender zutreffen, der dann noch auf einer anderen Webseite zu sehen wäre. Ich glaube, den Kalender sollten wir noch zurück stellen, bis das geklärt ist. Sowas wie Formelberechnung ist auch interessanter. Ich versuche mich da gerade an einem ML-Modell zur automatischen Erkennung, was für ein Mineral es wohl ist, um dann eine Formelberechnung durchführen zu können.

**Comment by MaraHochstein** [comment]
scheint wegen datenschutz nicht möglich zu sein, falls doch, dann reopen

**Comment by MaraHochstein** [comment]
scheint wegen datenschutz nicht möglich zu sein, falls doch, dann reopen
