### ISSUE TITLE
-- ternary diagrams

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#13]
@Hezel2000 
- Ich hatte mir als Notiz "Si-Fe-Mg ternary ?" aufgeschrieben. Für welches Mineral würde das Sinn machen?
- Du meintest, man solle sich aussuchen können, welche Oxide man an den Ecken hat? Kannst Du das ein wenig erläutern?

**Comment by Hezel2000** [comment]
Für praktisch alle, welche diese Elemente als Hauptelemente haben. Aber klar, mit Mineralen an den Ecken wäre es für manche Anwendungen noch praktischer. Letztlich wäre es später unproblematisch Felder für Minerale darin mit einzuzeichnen.

Wir haben gerade ein kleines Programm erstellt (fast fertig), mit dem wir alle Mineraldaten von mindat bekommen. Sobald das fertig ist, kann ich es Dir mal schicken, damit erhalten wir dann alle Mineralzusammensetzungen.

**Comment by MaraHochstein** [comment]
see https://github.com/MaraHochstein/EPMAdatatools/issues/26
