### ISSUE TITLE
++ duplicates in normal.txt

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#20]
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/df8f64f4-aa29-4cef-ac8c-8b1e0b82b7eb)
@Hezel2000 wird das normal-file manuell "copy-pasted"? Bei 411-ryo sind im normal-file die Daten doppelt vorhanden (alle Messwerte position 8 - 181, dann nochmal 8 - 181; Übergang siehe Screenshot). Ich versuche eine Kontrolle für doppelte Werte einzubauen, ich frage mich nur, ob das zufällig beim einfügen, oder durch den Export aus eurem EPMA-Programm passiert ist?

Dadurch funktioniert das merging der normal-file + summary.csv nicht richtig, was mir erst nicht aufgefallen ist (es werden einfach nur alle Werte doppelt angelegt und die Spalten nicht richtig umbenannt), bis ich mir die Mineralidentifikation zu diesem record angeschaut habe, die dann nicht auf die merged Spalten zugreifen kann...

Bitte die Datei von dem record nicht manuell anpassen!

**Comment by Hezel2000** [comment]
Alles klar, passe ich nicht an.
Sollte aber nicht passieren, die Maschinen-Software ist nicht der Knaller, kann schon sein, dass da was schief gelaufen ist. Da werde ich in Zukunft drauf achten. Alles Teil des Lernprozesses.

**Comment by MaraHochstein** [comment]
Die Datei könnte jetzt auch manuell angepasst werden (zum Platz sparen), aber für die Seite funktioniert es auch so. Die Duplikate werden jetzt vorher entfernt. Nur falls es ein Fehler des Gerätes wäre, könnte man das evtl beheben.
