### ISSUE TITLE
Funktions-Account

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#22]
Ich mache mir glaube ich zu viele Gedanken über diesen Funktionsaccount, aber ich bin noch nicht sicher, wie der funktionieren soll, daher noch mal dazu, weshalb ich damit noch nicht rumgekommen bin:

1. Für Accounts benötigt es eine email. D.h., ich muss mir eine email machen. Diese könnten dann verschiedenen Leute verwenden.  Da müsste ich mal schauen, ob ich eine solche von der Uni überhaupt bekommen könnte. Ich meine, ich hätte mir dazu mal eine email für eine email-Liste eingerichtet. Die Überlegung dazu habe ich leider vergessen, wenn ich die wieder finde, könnte ich die verwenden. Macht das Sinn?
2. Sollte ich dann sinnvoller Weise alle records dorthin verschieben? Damit das auch nach meiner Zeit sinnvoll verfügbar bleibt?
3. Wenn bei 2.: ja – könnte ich die Rechte wie bislang machen. Sonst müsste ich auch da einmal überlegen.

**Comment by MaraHochstein** [comment]
Die E-Mail-Adresse wäre für das EPMA - ob das von der Uni selbst ist, ist ja egal.. Ansonsten irgendeine Freemail.. Dazu hat ja dann auch keiner Zugriff. Du könntest den Kadi-Zugriff an die Personen weitergeben, die es benötigen.

Die records müssten meiner Meinung nach nicht dorthin verschoben werden, außer sie werden gelöscht, sobald Dein Account gelöscht wird. Ansonsten reicht es, wenn der Account Adminrechte an allen Guf-Group-records hat.
