### ISSUE TITLE
++ add Kadi Description

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#24]
Im Kadi record gibt es ein 'Description' Feld. Das wurde bislang etwas stiefmütterlich behandelt, gerade das soll zukünftig jedoch wichtige Informationen zum record/der Messung enthalten. Könntest Du das noch mit darstellen? Evt. direkt auf der Seite 'Data Import'?

**Comment by MaraHochstein** [comment]
Ja, warum bei Data Import und nicht bei den Kadi Metadata? Stehen dort relevante, nicht sensible Daten drin, die es sich lohnt bei Import darzustellen?

**Comment by Hezel2000** [comment]
Geht auch bei den Kadi Metadaten. Da dort keine wirklichen Metadaten stehen sondern eine Beschreibung über das Projekt/die Messungen, dachte ich könnte es evtl. beim Import passen. Schau mal was Du meinst, wo es besser passt, das wird dann auch gut sein.

PS: Mit 'stiefmütterlich' meinte ich übrigens mich beim Hochladen der Daten.

**Comment by MaraHochstein** [comment]
Alles klar, ich dachte, es gibt einen besonderen Grund für die Darstellung beim Import, aber eigentlich halte ich es dort für verschwendet. Ich würde es eher bei den Kadi Metadata aufführen, weil man das vielleicht auch mit exportieren möchte. Ansonsten sehe ich nicht den Vorteil, darüber einen record besser zu finden oder so..

**Comment by MaraHochstein** [comment]
Einmal bei den Kadi Metadata (zum Export) und einmal als Info in der Sidebar:
![grafik](https://github.com/user-attachments/assets/f9705c08-e306-44b2-8c86-53bbfdf73ae9)
