### ISSUE TITLE
User Feedback

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#27]
Ich kopiere hier mal User Feedback rein (soweit ich etwas bekomme). Das kannst Du je nachdem wie hilfreich/zutreffend es ist aufnehmen oder einfach wieder streichen.

Einige Dinge, die mir aufgefallen sind oder passiert sind:
- Zwischendurch hat sich die Seite beim Laden der Bilder einfach zurückgesetzt und ich landete wieder auf der Startseite.
- Das Eingabefeld für das Dataset scheint bei jeder Eingabe die komplette Datenbank zu durchsuchen, was dazu führte, dass die Seite abstürzte und ein Error 503 angezeigt wurde. Das war zunächst reproduzierbar, danach waren die Daten wohl im Cache und es funktionierte ohne Absturz.
- Wenn man etwas eingibt, das kein Treffer in der Datenbank hat, kann es ebenfalls zu einem Absturz kommen und die Seite bleibt in einer Schleife hängen, bis sie neu geladen wird. Das war allerdings nicht reproduzierbar.
 
Positiv:
- Das Excel-Sheet finde ich super. Ich bin mir nicht sicher, ob es nützlich wäre, noch weitere Daten wie „detection limit“ und die „Fehler“ hinzuzufügen, oder ob das nicht notwendig ist.
- Der Export der Bilder funktioniert ebenfalls sehr gut. Allerdings wird man mehrmals auf die Startseite zurückgeworfen, wenn sehr viele Bilder geladen werden und dadurch eine lange Ladezeit entsteht. Das Kompilieren wird dabei nicht abgebrochen, was sehr gut ist.
 
Verbesserungsvorschläge:
- Ich fände es gut, wenn der User nicht extra das Kompilieren des Foto-Zips starten müsste. Vermutlich gibt es hier aber wohl Begrenzungen in der Rechenleistung oder der Datentransfer-Menge, sodass dies nicht automatisch gestartet werden kann?
- Es wäre auch schön, mehrere Datasets gleichzeitig laden zu können oder alternativ auf der Import-Seite ebenfalls einen „clear data“-Knopf zu haben und nicht nur unterhalb der Navigationsleiste links.
- Das .zip-File hat keinen eindeutigen Namen. Wenn es das Datum-Format des Excel-Sheets oder den Namen des Datasets übernehmen würde, fände ich das praktischer. So müsste das Zip nicht immer umbenannt werden, um ein versehentliches Überschreiben mit einem neuen Zip eines Datasets zu vermeiden.

**Comment by MaraHochstein** [comment]
Allgmeien: Bitte bei **allem** immer record bsp, sonst kann ich nichts nachvollziehen oder nachtesten... gerade bei den img-Sachen, oder "komischem" Seitenverhalten.
---

1. Die Seite sollte sich eigentlich nicht während des Ladens zurücksetzen, das passiert eigentlich nur, wenn man selbst refreshed. Ansonsten bitte record bsp
2. Punkt 2 verstehe ich nicht. Welches "Eingabefeld" scheint welche "Datenbank" zu durchsuchen? Das wird alles gecached.
3. Wo wird etwas eingegeben? Es gibt eigentlich nur ein dropdownfeld, aus dem man auswählt. Ein Dropdown ist nicht zum eintippen gedacht, sonst wäre es ein Textfeld?
4. Wenn etwas bei dem Excelfile hinzugefügt werden soll, bitte neues issue mit konkreten Punkten
5. Wieder bitte bsp, ich werde nie auf die Startseite zurückgeworfen, außer man reloaded die Seite (ist gewollt und eine eingebaute Funktion!)
6. Wie schon mal in einer Mail geschrieben, das ist absolut unvorteilhaft umzusetzen. 1. Würde das Aufrufen der Export Seite bei vielen Bildern ewig dauern bzw ewig zu ende rendern, was dann zu Komplikationen führt, wenn der user zwischendurch rumklickt. Außerdem ist es total ärgerlich, wenn man überhaupt keine Bilder exportieren möchte. Auch die Funktion wird gecached, sodass das nur 1x gemacht werden muss, _falls_ man es möchte. Es geht, aber es wäre absolut user-unfreundlich.
7. Mehrere datasets gleichzeitig = viel mehr gespeicherte daten etc. Wenn ich bedenke, was noch an Extras kommt (muss auch alles in session_state), dann würde das nur zu längeren Ladezeiten führen. Und bis auf, dass 1 user mehrere "Teile" gemessen hat, gibt das auch keinen Vorteil, weil die user für gewöhnlich nur ihr eigenes dataset laden. Zum data clear button zusätzlich: ist kein Problem, das hinzuzufügen, aber total redundant. Wenn man einmal weiß, dass dort der Knopf ist, dann hat man das schneller geklickt und es ist immer in der Sidebar zur Verfügung und einfach zugänglich. Ich sehe da persönlich nicht den Sinn, zusätzliche redundante Buttons hinzuzufügen..
8. Es sollte eigentlich der record name im Namen auftauchen, es war eine falsche Bedingung drin, sollte jetzt richtig funktionieren.

**Comment by Hezel2000** [comment]
Ja, stimmt natürlich, hatte ich vergessen. Es ging um die ErGr records.

Nutzer Feedback ist immer eine zweischneidige Sache. Ich stimme Dir bei eigentlich allem zu. Ich hatte erst mal gedacht, das hier ein wenig zu sammeln. Wenn man auf alles eingeht, was einem oder einer Nutzerin bei der ersten Bedienung einfällt wird das Ergebnis nichts sinnvolles. Wie gesagt, mehr zum sammeln, überlegen und dann weiter sehen. Ich sehe da aktuell auch keinen echten Handlungsbedarf.
