### ISSUE TITLE
? maps brauchen keine summary, normal, csv Dateien

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#29]
Es kann records geben, die keine Analyse Daten enthalten, und somit auch keine summary, normal, oder csv Dateien enthalten. Ein Bsp ist record @guf-ifg-epma-20240425-shsi. Die können im Moment nicht geladen werden. Entweder fällt die Ueberprufung nach den Dateien weg, oder das muss z.B. in den Metadaten entsprechend vermerkt werden. Wie funktioniert das denn gerade mit einem Map Datensatz? Du hattest ja erst diese schöne Oberfläche dazu programmiert?

**Comment by Hezel2000** [comment]
Ich habe gerade den Fall einer Messung mit Punktanalysen und element maps. Dabei ist mir aufgefallen, dass wir hier eine grundsätzliche Entscheidung brauchen. Punktanalysen und element maps haben beide ein 'quick standard.txt' file. Element maps haben nur das. Wenn ich nun aber Punktanalysen und element maps in einen record lade, würde ich dort 2  'quick standard.txt' files hoch laden, was natürlich keinen Sinn macht. D.h., entweder muss ich (i) für Punktanalysen und element maps 2 separate records machen, oder ich muss (ii) das 'quick standard.txt' file für die element maps umbenennen.

Ich bin gerade etwas unentschlossen, würde im Moment aber zur Lösung (ii) tendieren.

Für den aktuellen Fall lege ich noch mal 2 records an (und lade 3 dummy files für summary, normal, csv Dateien hoch, damit das klappt), damit der user damit arbeiten und auch mal ein bisschen das map-tool ausprobieren kann.

**Comment by Hezel2000** [comment]
Noch eine letzte Bemerkung, da ich gerade an einem entsprechenden record bin, wie im letzten Kommentar angemerkt.
Mir ist auch noch aufgefallen, dass wir glaube ich für die maps eine zusätzliche Information abgelegt haben. Ich bin nicht mehr sicher, was das war, evtl. 'additional measurement parameters.json'. Die habe ich nun zumindest noch mit dazu genommen, zumindest im record:
@guf-ifg-epma-20240826-clack
Mit dem Du gerne mal testen kannst. Der enthält nun auch die Punktanalyse-files, aber nur, da ich sonst einen Fehler erhalte.
Die Map-Controls sind in der aktuellen Version noch nicht drin, korrekt?
Ich verwende:
https://epmatools.streamlit.app

**Comment by MaraHochstein** [comment]
bei maps "quick standard maps.txt", ansonsten "quick standard.txt"

**Comment by MaraHochstein** [comment]
@Hezel2000 wo sollen die additional map parameters dargestellt werden?
![grafik](https://github.com/user-attachments/assets/a013d137-bfd2-4ae2-80c4-cd6d8bc82a28)

**Comment by MaraHochstein** [comment]
@Hezel2000 Enthalten "only map" datasets NUR den "quick standard maps.txt" und NICHT "summary standard.txt"?

**Comment by Hezel2000** [comment]
Ja genau, die haben dann nur 'quick standard maps.txt'.

**Comment by MaraHochstein** [comment]
okay 👍
