### ISSUE TITLE
++ add standards.xlsx file

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#30]
Ich habe angefangen eine weitere Datei hinzu zu fügen, die evtl. optional ist (vermutlich wird sie immer dabei sein) und 'standards.xlsx' heißt. Könnte die unter einem weiteren Reiter neben Metadata - Measurement Condition - Method Writeup stehen. Es ist eine Excel-Datei, da sie formatiert ist und farbige Felder enthält. Die sollte natürlich auch im Download mit dabei sein.

Über das den Inhalt des Description-Feld von Kadi hatten wir glaube ich schon gesprochen. Ich bin nicht sicher, ob das schon drin ist, ich habe es zumindest nicht entdeckt.

**Comment by MaraHochstein** [comment]
unter measurement conditions -> neuer tab "standards" -> nur darstellen, aber original in download (wegen formatierung)

**Comment by MaraHochstein** [comment]
@Hezel2000 

Ich habe mir jetzt von den letzten records die standards.xlsx angesehen, und drei verschiedene Varianten des Inhaltes gefunden.. Wie soll es am Ende einheitlich sein? Oder soll es unterschiedlich sein?

- Variante 1: ein Blatt "standards", in dem eine Tabelle ist (z. B. GUF IfG EPMA 20241104 WaJa)
- Variante 2: ein Blatt "standards", in dem zwei Tabellen untereinander sind (bei GUF IfG EPMA 20241104 AtUr):
![grafik](https://github.com/user-attachments/assets/044d32eb-a5c5-4082-b52c-4f15bbb0a442)
- Variante 3: mehrere Blätter mit verschiedenen Datumsangaben als Namen, in denen jeweils eine Tabelle ist - interessanterweise haben die drei Beispiele, in denen das vorkam, alle die gleichen beiden Blattbezeichnungen "22.07.2024" und "24.07.2024", jedoch jeweils unterschiedlichen Inhalt im Blatt "24.07.2024", das andere Blatt ist jeweils gleich
(z. B. GUF IfG EPMA 20241017 Ji, GUF IfG EPMA 20241031 CeOg, GUF IfG EPMA 20241024 BrAr, GUF IfG EPMA 20241001 SoAu)
![grafik](https://github.com/user-attachments/assets/250a8a2b-55f6-4694-a39b-ce1da8fadf85)

Falls mehrere Tabellen dargestellt werden _sollen_, dann lieber in einzelne Blätter als untereinander in ein Blatt, das lässt sich viel einfacher auslesen...

**Comment by MaraHochstein** [comment]
z.t. fertig
![grafik](https://github.com/user-attachments/assets/52f12b40-2605-49f7-bed1-b5d8699105f5)

**Comment by MaraHochstein** [comment]
aktuell gebe ich einen Fehler aus, wenn es nicht Variante 1 von oben ist (also mehr als ein Blatt / mehr als eine "Tabelle" auf einem Blatt). Alle richtig formatierten standards.xlsx sollten korrekt laden (mit Farbgebung) - export folgt noch

**Comment by MaraHochstein** [comment]
Excel Export hinzugefügt

Unklarheiten bezüglich standards.xlsx-Format in neuem Issue
