### ISSUE TITLE
Es werden nicht alle quantitativen Daten geladen

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#37]
Bevor ich da lange schreibe, habe ich ein kurzes Video gemacht, schau mal, ob Du daraus schlau wirst:
https://vimeo.com/1029312715?share=copy#t=0

**Comment by MaraHochstein** [comment]
Dazu hatte ich schon mal ein Issue aufgemacht, weil es mir aufgefallen ist: https://github.com/MaraHochstein/EPMAdatatools/issues/20

Da war aber die "Lösung", dass es wohl nur aus Versehen ein Fehler war.. Und ja, die werden anhand der Nummer zusammengejoined, wobei ich halt dann die Duplikate entfernt habe...

**Comment by MaraHochstein** [comment]
über die comments zusammenzuführen ist eine Idee, das könnte ich versuchen - bzw. hoffen, dass die user eben nicht aus Versehen zwei Punkte gleich nennen.. optimal wäre, wenn der Messzeitpunkt auch im standard...csv stehen würde, das wäre dann wirklich eindeutig, aber lässt sich vermutlich nicht einstellen, oder?

Ansonsten: kann man nicht bei der Firma ein ticket aufmachen, dass die ihre Software dahingehend korrigieren? 😅 ist ja eigentlich nicht richtig, dass beim Zusammenführen die Points im normal file nicht angepasst werden..

**Comment by Hezel2000** [comment]
Die Stage position könnte unique sein im summary und im normal file.

**Comment by Hezel2000** [comment]
… wenn ein Name doppelt vergeben ist, wäre es wie bei z.B. Pandas möglich, dass die doppelte (oder dreifachen…) ein .1, .2, .x nachgestellt bekommen?

**Comment by MaraHochstein** [comment]
> Die Stage position könnte unique sein im summary und im normal file.
Die Wahrscheinlichkeit ist hoch, aber im Extremfall könnte es auch gleich sein, denke ich..

> … wenn ein Name doppelt vergeben ist, wäre es wie bei z.B. Pandas möglich, dass die doppelte (oder dreifachen…) ein .1, .2, .x nachgestellt bekommen?
Hm, ja denke schon. Wobei ich es eigentlich erstmal über den Comment so machen würde (normalerweise bezeichnet man nicht zwei Proben gleich?) und evtl eine Info-Ausgabe, dass doppelte Kommentare vorhanden sind und man sich bitte melden soll.. Eigentlich möchte man wenig um user-Fehler herumbasteln 😂 Bzw ich würde den Punkt erstmal hinten anstellen (muss noch die daten zu den maps auslesen und importieren) und hinterher als to do aufschreiben.

**Comment by MaraHochstein** [comment]
Lädt jetzt richtig (merge über comment)

**Comment by MaraHochstein** [comment]
GUF IfG EPMA 20241001 SoAu hat Duplikate in "Comment", es wird jetzt ein '_dupe' für Duplikate angehängt
![grafik](https://github.com/user-attachments/assets/993b55c6-3566-4ecf-82c7-95972322f0c3)

**Comment by Hezel2000** [comment]
Das sieht gut aus. In pandas wird das ja über xxx.1 gelöst. Und wenn es mehr gibt über xxx.2, xxx.3, ... Daher meine Frage: falls es jemand schafft, einen Messpunkt mehrfach gleich zu benennen (es gibt so verschobene Typen), klappt das dann mit 'dupe' auch?

**Comment by MaraHochstein** [comment]
duplicates werden jetzt durchnummeriert
![grafik](https://github.com/user-attachments/assets/552f5a66-b504-4ad2-bd0f-fcc485e9de80)

**Comment by Hezel2000** [comment]
Sieht sehr gut aus.
