### ISSUE TITLE
+++ map files in GUF IfG EPMA 20241104 AtUr sind falsch benannt

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#38]
Map files sollten immer mit "map[Leerzeichen]" anfangen, so wie bei "Demo Maps" und abgesehen innerhalb Bezeichnung sollten die weiteren Spezifikationen immer mit Leerzeichen getrennt sein:

![grafik](https://github.com/user-attachments/assets/5df27e15-8a8d-4621-8c73-bbe647508a0c)

map[Leerzeichen][Bezeichnung][Leerzeichen]["EdsData" oder "data"][nummer z.B. 001, 002, 003 etc.][Leerzeichen]{Element][Ka oder La].csv

also z.B. "map 1 data001 Na Ka.csv"

in  GUF IfG EPMA 20241104 AtUr heißen sie: "JB-1-Grt-3 Ti-Ka.csv" müsste aber, falls "JB-1-Grt" die Bezeichnung der Probe sein soll, so heißen:
"map JB-1-Grt EdsData003 Ti Ka.csv" bzw.
"map JB-1-Grt data003 Ti Ka.csv", je nachdem, ob EDS oder nicht.

**Comment by Hezel2000** [comment]
Ah, OK, ich habe die jetzt immer nur nach dem Probennamen benannt. Da müsste ich noch mal in einige records rein gehen. Ich könnte das ab sofort so machen, und müsste das bei der einen großen Umbenennung irgendwann dann noch mal für alle map-Dateien ändern.

Soll ich das so machen?

**Comment by MaraHochstein** [comment]
Ja, dann am besten immer wie oben geschrieben:
map[Leerzeichen][Probenname]["EdsData" oder "data"][nummer z.B. 001, 002, 003 etc. kann auch ohne die Nullen sein][Leerzeichen]{Element][Ka oder La].csv
über das "map" identifiziere ich sie als map-data und die restlichen Sachen ziehe ich dann für die anderen Informationen daraus. Es kann auch (wenn es einheitlich für alle ist) dann statt Leerzeichen ein Unterstrich sein und innerhalb des Probennamens nur Bindestriche, das ist mir egal ;)

**Comment by MaraHochstein** [comment]
Ja passt fast, aber jetzt hast Du das Leerzeichen zwischen Element und Linie vergessen 😅 

![grafik](https://github.com/user-attachments/assets/54368129-c39d-468a-9dc2-b67a99ef30a7)

Ich kann es aber für den Record selbst anpassen, aber vielleicht änderst Du das nochmal in Deinem Script?

**Comment by Hezel2000** [comment]
Ah, OK, dann hatte ich das falsch verstanden. Im Skript ist es schnell geändert, soll ich die dann noch mal neu hochladen?

**Comment by MaraHochstein** [comment]
Für [GUF IfG EPMA 20241126 WaJa](https://kadi4mat.iam.kit.edu/records/43432) habe ich es manuell angepasst, das passt so
