### ISSUE TITLE
++ add info from "additional measurement parameters.json" to maps

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#39]
![384051660-a013d137-bfd2-4ae2-80c4-cd6d8bc82a28](https://github.com/user-attachments/assets/b0794f29-dc19-4eb2-95c5-dab7c134042d)

**Comment by MaraHochstein** [comment]
@Hezel2000 Das neue json sieht erstmal gut aus! Falls es Fragen gibt, melde ich mich hier

**Comment by MaraHochstein** [comment]
(schon per Mail, aber hier für mich als Übersicht)
![zSygJ0evDw0EVo6h](https://github.com/user-attachments/assets/d33c3c22-11db-41a6-b31d-c2970ab90eb6)
Ist das so richtig? Bei den quantitative conditions war es z.B. 19.2 nA, kann mir nicht vorstellen, dass das um 7 Einheiten kleiner ist?

**Comment by MaraHochstein** [comment]
![grafik](https://github.com/user-attachments/assets/c613aeb7-48ba-4e53-9ae4-eb56115dd53a)
hier sind zwei Koordinaten angegeben (x, y), aber drei Werte?

**Comment by Hezel2000** [comment]
> (schon per Mail, aber hier für mich als Übersicht) ![zSygJ0evDw0EVo6h](https://private-user-images.githubusercontent.com/117297458/393268180-d33c3c22-11db-41a6-b31d-c2970ab90eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQzMDksIm5iZiI6MTczMzQ5NDAwOSwicGF0aCI6Ii8xMTcyOTc0NTgvMzkzMjY4MTgwLWQzM2MzYzIyLTExZGItNDFhNi1iMzFkLWMyOTcwYWI5MGViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDA2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmMwNzZjZjdkMTRkMDQ0NmFmMDFlZDkyMzI3ODAyMmNmYjU4ODllOTkxOWE5MTU2NmVlODE3Y2FlNzVkNTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8GAHJtY9k9nQYcwNbOzJRYC2qthN8dU7LHS6J4SeCEs) Ist das so richtig? Bei den quantitative conditions war es z.B. 19.2 nA, kann mir nicht vorstellen, dass das um 7 Einheiten kleiner ist?

Oh, richtig. Die Angabe ist in A, ich bin nur nA so gewohnt. Die Ausgabe sollte auch in nA sein, d.h., hier wäre eine Umrechnung mal 10^9 nötig, um auf die korrekten 300 nA zu kommen. Soll ich die Umrechnung bei mir einbauen? Wäre evtl. für die Performance besser, wenn Du das nicht machen müsstest.

**Comment by Hezel2000** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/117297458/393268465-c613aeb7-48ba-4e53-9ae4-eb56115dd53a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQzMDksIm5iZiI6MTczMzQ5NDAwOSwicGF0aCI6Ii8xMTcyOTc0NTgvMzkzMjY4NDY1LWM2MTNhZWI3LTQ4YmEtNGU1My05YWU0LWViNTYxMTVkZDUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDA2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTg4ZWE0ZGNlYjJjNDVkMTNiMzMyMzkzOTc4MmZjMjZjMTU2NmNhMGVjYTQzNGQxY2NkNDI1MTdiOGM5MTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5zY2m-oBdyMCyRmkankW5d97v4_r7bh0R1-q0HuyW6s) hier sind zwei Koordinaten angegeben (x, y), aber drei Werte?

Richtig, das hat mich auch schon irritiert. Ich bin nicht 100% sicher, was die dritte Zahl ist, die würde ich ignorieren, die wichtigen sind die ersten beiden Zahlen.

**Comment by MaraHochstein** [comment]
> > ![grafik](https://private-user-images.githubusercontent.com/117297458/393268465-c613aeb7-48ba-4e53-9ae4-eb56115dd53a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQzMDksIm5iZiI6MTczMzQ5NDAwOSwicGF0aCI6Ii8xMTcyOTc0NTgvMzkzMjY4NDY1LWM2MTNhZWI3LTQ4YmEtNGU1My05YWU0LWViNTYxMTVkZDUzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxNDA2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTg4ZWE0ZGNlYjJjNDVkMTNiMzMyMzkzOTc4MmZjMjZjMTU2NmNhMGVjYTQzNGQxY2NkNDI1MTdiOGM5MTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5zY2m-oBdyMCyRmkankW5d97v4_r7bh0R1-q0HuyW6s) hier sind zwei Koordinaten angegeben (x, y), aber drei Werte?
> 
> Richtig, das hat mich auch schon irritiert. Ich bin nicht 100% sicher, was die dritte Zahl ist, die würde ich ignorieren, die wichtigen sind die ersten beiden Zahlen.

Ok 😅

**Comment by Hezel2000** [comment]
Sieht gut aus. Brauchst Du dann noch die Info welche Parameter evtl nicht dargestellt werden? Eigentlich ist nur optional, ob WDS und/oder EDS enthalten sind.

**Comment by MaraHochstein** [comment]
nur, falls noch zusätzliche zeilen kämen, die bisher nicht aufgeführt waren

**Comment by Hezel2000** [comment]
Eigentlich sollte das nun so bleiben.

**Comment by Hezel2000** [comment]
Comment
Pixel size
Dwell time

**Comment by MaraHochstein** [comment]
@Hezel2000 comment ist jetzt in dem json von Dir aber nicht drin 😅

**Comment by Hezel2000** [comment]
Ah, evtl. hatte ich den schon rausgenommen, da die Datei schon so heißt. Evtl. mache ich den wieder in das json rein, kann dann aber unbeachtet bleiben.

**Comment by MaraHochstein** [comment]
Details sind jetzt bei den maps, allerdings habe ich es aus Platzgründen in den hover gesteckt:
![grafik](https://github.com/user-attachments/assets/5604c661-d8ec-4a01-ac1f-a377ed6cf6dc)

**Comment by Hezel2000** [comment]
Im Hover ist das mE perfekt untergebracht.
