### ISSUE TITLE
+ show metadata

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#4]
show metadata from kadi
----
status:
- [x] get metadata
- [x] show in data viewer
- [ ] styling / only specific metadata?

**Comment by MaraHochstein** [comment]
@Hezel2000 Sind die Metadaten-Felder immer fest (mehr oder weniger, mal kann ein Feld leer sein), oder unterscheiden sie sich bei den records?

**Comment by Hezel2000** [comment]
Die sind fest und ja, manchmal leer. Es kann aber sein, dass die noch mal etwas angepasst werden.

**Comment by MaraHochstein** [comment]
Ok, also werden immer alle Felder angelegt, aber nicht ausgefüllt? (das wäre wahrscheinlich optimal)
Dann verwende ich für die Darstellung die Metadaten eines neueren records.

**Comment by MaraHochstein** [comment]
@Hezel2000 Sollen die Metadaten in einem eigenen Tab dargestellt werden, oder unter den Measurement Conditions --> General Info? Diese sind ja aus den Messfiles selbst.. Wenn ich die Daten für chrilloi vergleiche, ist das ein wenig verwirrend (bezüglich z.B. Comment und Project, auch der SavedPath enthält hier einen anderen Namen als in den Metadaten
(s. Mail)

**Comment by Hezel2000** [comment]
Ich würde 4 tabs machen:
Kadi Metadata – Selected Measurement Conditions – Method Writeup – All Measurement Conditions

**Comment by MaraHochstein** [comment]
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/959afa6d-c56d-4371-ac7b-b7a7f3eda336)

**Comment by Hezel2000** [comment]
Ja, so soll es aussehen. Evtl. reicht ›Metadata‹ und bei den ersten Measurement conditions könnte ›Selected‹ auch weg.
