### ISSUE TITLE
++ einheitliches Format in standards.xlsx auf kadi

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#41]
@Hezel2000 

Ich habe mir jetzt von den letzten records die standards.xlsx angesehen, und drei verschiedene Varianten des Inhaltes gefunden.. Wie soll es am Ende einheitlich sein? Oder soll es unterschiedlich sein?

- Variante 1: ein Blatt "standards", in dem eine Tabelle ist (z. B. GUF IfG EPMA 20241104 WaJa)
- Variante 2: ein Blatt "standards", in dem zwei Tabellen untereinander sind (bei GUF IfG EPMA 20241104 AtUr):
![grafik](https://github.com/user-attachments/assets/044d32eb-a5c5-4082-b52c-4f15bbb0a442)
- Variante 3: mehrere Blätter mit verschiedenen Datumsangaben als Namen, in denen jeweils eine Tabelle ist - interessanterweise haben die drei Beispiele, in denen das vorkam, alle die gleichen beiden Blattbezeichnungen "22.07.2024" und "24.07.2024", jedoch jeweils unterschiedlichen Inhalt im Blatt "24.07.2024", das andere Blatt ist jeweils gleich
(z. B. GUF IfG EPMA 20241017 Ji, GUF IfG EPMA 20241031 CeOg, GUF IfG EPMA 20241024 BrAr, GUF IfG EPMA 20241001 SoAu)
![grafik](https://github.com/user-attachments/assets/250a8a2b-55f6-4694-a39b-ce1da8fadf85)

Falls mehrere Tabellen dargestellt werden _sollen_, dann lieber in einzelne Blätter als untereinander in ein Blatt, das lässt sich viel einfacher auslesen...

_Originally posted by @MaraHochstein in https://github.com/MaraHochstein/EPMAdatatools/issues/30#issuecomment-2497625583_

**Comment by Hezel2000** [comment]
Da habe ich einen Fehler gemacht, da ich die 'standard.xlsx' Datei immer wieder über copy&paste dupliziert habe, und dabei versehentlich dieses erste Tabellenblatt mitgeschleppt habe. Natürlich soll es nur ein Tabellenblatt geben, das muss ich auch noch korrigieren.

Allerdings kann es sein, dass es mehr als nur eine solche Tabelle gibt. Ich dachte dann, eine zweite, dritte, .... falls nötig im selben Tabellenblatt darunter zu machen. Würde das funktionieren? Also Variante 2.

Ansonsten: schick.

**Comment by MaraHochstein** [comment]
Variante 2 wäre die ekeligste 😅  falls es mehrere geben soll, dann bitte andere Blätter.. Im Export kann ich das auch wieder auf ein Blatt untereinander machen, aber zum Importieren ist das grausig..

Warum gibt es denn mehrere Tabellen? Sind das zwei Messungen, über die dann gemittelt werden soll? Oder sind sie tatsächlich mit verschiedenen Datumsangaben? Wenn ersteres, dann wäre es vielleicht gut, die Blätter einfach 1,2,3... durchzunummerieren, wenn zweiteres, dann die Datumsangaben (könnte man ja dann mit darstellen). Oder ein anderer Grund?

**Comment by Hezel2000** [comment]
OK, mehrere Blätter sind auch kein Problem (das wird irgendwann noch lustig, all die records durchzugehen und zu korrigieren, aber das wird schon klappen).

Mehrere Tabellen, da manchmal während einer Messung nochmals kalibriert oder nachkalibriert wird. Ich kann die Datumsangabe auch direkt auf die Blätter machen, statt Comment in Zelle A1.

**Comment by MaraHochstein** [comment]
Wenn die Messungen einfach mehrere Kalibrierungen sind, wäre es vielleicht am einfachsten, wenn die Blätter dann einfach durchnummeriert werden 1,2,3...

**Comment by Hezel2000** [comment]
OK.

**Comment by MaraHochstein** [comment]
@Hezel2000 
Was ist denn hier passiert (rote Kästchen)? Das sollte so nicht richtig sein? Eine Spalte ohne Titel und Text als "Messwerte"?

Zu den grünen Kästchen: da wäre es mir dann lieber, wenn statt dem Datum oben als Header, die Blätter nur so heißen wie das Datum (falls mehrfach an einem Tag, dann z.B. "28.11.2024-1" / "28.11.2024-2", da ich die sheets eh in einem dict speichere, kann ich dann einfach den key auslesen und noch als subheader darstellen, das sieht übersichtlicher aus als wenn man das als header hat. So geht das irgendwie unter. Statt "Comment" (wie vorher) sollte dann da aber eher "Standard" stehen oder so..

![grafik](https://github.com/user-attachments/assets/87310ed1-64f5-4fd3-80d0-2bd764a87a30)

**Comment by MaraHochstein** [comment]
- [x] mehrere Blätter können geladen und exportiert werden

**Comment by MaraHochstein** [comment]
alles klar :)

ToDo für mich:
-[] Überschriften

**Comment by MaraHochstein** [comment]
die neuen records haben jetzt wieder das Datum in A1, statt als Blattname, das sieht dann weniger hübsch aus
![grafik](https://github.com/user-attachments/assets/8585115e-7424-4849-8e83-e885f32add33)

**Comment by Hezel2000** [comment]
Da hat mich der Alltag eingeholt. Das korrigiere ich.
