### ISSUE TITLE
+++ add maps

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#42]
ToDo

- [x] neue map bezeichnungen übernehmen
- [x] filter anpassen
- [x] json einbinden

nur als Info: die Auswahl der "samples" im map filter habe ich als "single"-select gemacht, alles andere sind multiselects. Ist glaube ich nicht nötig, mehrere verschiedene "maps" gleichzeitig zu sehen und damit es sich bei vielen maps nicht aufhängt  / ewig lädt, habe ich die Auswahl da beschränkt. Elemente möchte man natürlich verschiedene von einem sample nebeneinander sehen.

Damit das etwas hübscher aussieht als mit den normalen multiselect-dropdowns, habe ich die  neuen Funktionen st.pills und st.segmented_control benutzt

![grafik](https://github.com/user-attachments/assets/1dab871e-c3dd-4a39-85e8-00af69f9d839)

**Comment by Hezel2000** [comment]
Sieht soweit gut aus. Wie es funktioniert müsste ich dann mal ausprobieren.

**Comment by MaraHochstein** [comment]
bin dran ;)

**Comment by MaraHochstein** [comment]
wird morgen voraussichtlich fertig & released

**Comment by Hezel2000** [comment]
top!
