### ISSUE TITLE
++ short form of the measurement conditions 

### ISSUE THREAD

**Issue by Hezel2000** [MaraHochstein/EPMAdatatools#5]
- [x] kV
- [x] nA
- [x] Spotsize

- [ ] Messprogramm als Tabelle:
<img width="450" alt="image" src="https://github.com/MaraHochstein/EPMAdatatools/assets/86461739/aa022a97-a5f0-4398-85eb-4d6f4c52e1ce">

**Comment by Hezel2000** [comment]
Wir hatten 2 tabs bei der Ausgabe der Messparameter: einmal die volle, und einmal eine Kurzversion. Sobald der Demo- oder ein anderer Datensatz erreichbar ist (war ja mein Fehler) kann ich einen Screenshot von der Stelle machen, die ich meine.

**Comment by MaraHochstein** [comment]
@Hezel2000 wo finde ich "kV" und "Spotsize"? Die finde ich bei den ausführlichen Metadata nicht

**Comment by Hezel2000** [comment]
Ja, die waren in einem der anderen files normal oder standard. Die hattest Du dort schon mal extrahiert.

**Comment by MaraHochstein** [comment]
Ah, die sind nur in dem Writeup.. Ist spotsize die "1 µm" in "The spot analyses were performed with a focused beam of 1 µm diameter" und kV wahrscheinlich die 15 aus "The accelerating voltage was set to 15.0 kV"?

**Comment by MaraHochstein** [comment]
die kurze und lange Darstellung mache ich als einzelne Untertabs, sonst ist die Menü-Anordnung nicht sinnvoll
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/7636902e-4f3c-4383-bf9a-a0e48b1ccba5)

**Comment by Hezel2000** [comment]
Mir scheinen das dann doch etwas viele subtabs. Eventuell als Titel einfach nur ›conditions‹ und ›full conditions‹? Dann wird es kürzer. Die Conditions will man doch öfter haben, das sollte man nicht so viel klicken. Full Conditions werden sicherlich seltener angeschaut, sind aber sehr hilfreich, wenn man sie mal braucht.

**Comment by MaraHochstein** [comment]
Ich sehe das Problem nicht, weil der erste Tab immer automatisch geladen wird. So muss man zwar spezifisch auf Full klicken, um alle zu sehen, aber man braucht es ja wie du sagst fast nie. Daher fände ich es in einer übergeordneten Überschrift unsinniger

**Comment by MaraHochstein** [comment]
@Hezel2000 Woher bekomme ich das detection limit? das finde ich nirgendwo in den rohdaten.. Und woher bekomme ich die spotsize? Die steht so auch nicht in den txt-files, es gibt nur je Messpunkt einen "probe diameter", aber die könnten sich ja auch unterscheiden und dann wäre es keine feste Zahl..

**Comment by Hezel2000** [comment]
Das detection limit ist in der Datei mit dem Datum.
Ja, die Spotsize kann variieren. Da könnte man mit .unique() schauen wie das variiert und das reporten als:
1. In der Tabelle: Spotsize, 1, 6, 10 µm – also einfach eine Liste aller verwendeten spotsizes
2. Im Text: Standard spotsize is 1 µm, and 6 µm for beam instable minerals. Denn das ist der primäre Grund weshalb die Spotsize aufgedreht wird. Natürlich gibt es noch andere Gründe, da muss ein user dann halt entsprechend anpassen. Es ist ja schon hilfreich wenn man sieht, welche spotsizes man überhaupt verwendet hat. In der Regel sind das nicht mehr als 2, meist nur eine.

**Comment by MaraHochstein** [comment]
@Hezel2000 nochmal genau: 
1. ist "probe diameter" = "spotsize"?
2. ich finde nichts als einzelne detection limits.. in der "Datei mit dem Datum" (summary.csv?) sind zwar "D. L." (detection limits?), allerdings sind die ja für jeden Messpunkt und nicht für jeden Standard? Es sind zumindest alles unterschiedliche Werte, s. hier:
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/ec748e7a-9feb-4c56-86f5-4f8f7056cafd)
oder soll das da aus der Spalte auch jeweils max & min sein?
Sonst schick bitte einfach kurz einen screenshot, wo du das auf kadi in der datei siehst (man kann sie ja dort alle sehen), dann finde ich die Stelle auch so

**Comment by Hezel2000** [comment]
1. Ja, spotsize = probe diameter
2. Richtig, hatte ich vergessen. Es wird für jeden Punkt ein dl berechnet. etwa overkill und unnötig. Ich würde sagen: den Median, evtl. noch ±stdev. Die Bandbreite dürfte sehr schmal sein, und den Median, falls es doch mal einen Ausreißer geben sollte.

**Comment by MaraHochstein** [comment]
Spotsize done
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/610b7927-553f-4dd1-975d-c7f644011f3d)

**Comment by MaraHochstein** [comment]
@Hezel2000 Zu den detection limits:
also dann aus der summary csv alle D.L. eines Elementes -> Median -> und dies dann bei den Standards als "Detection Limit"?
Was für eine Einheit ist das? Also bei Na z.B. ~ 70 ...?

**Comment by Hezel2000** [comment]
Genau. Das sollten eigentlich immer Gewicht PPM sein.

**Comment by MaraHochstein** [comment]
![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/93c9a357-0e67-4926-867b-1e75bd86f7a2)

**Comment by MaraHochstein** [comment]
@Hezel2000 du meintest bei dem detection limit ppm, nicht wt%, oder?

**Comment by Hezel2000** [comment]
Genau, d.l. ist in ppm. Allerdings sollte die Einheit wt-ppm sein oder µg/g. ppm ist wie % nur eine Art Mengenangabe, der aber noch die Einheit fehlt.

**Comment by MaraHochstein** [comment]
ist angepasst
