### ISSUE TITLE
new example dataset

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#7]
with
- some images (< 100)
- metadata
- known px & ol? (for ternary diagrams)

**Comment by Hezel2000** [comment]
Metadaten haben nun alle Datensätze, Die aktuellen datasets haben fast immer Bilder. Als ternäres Diagramm könnte man auch eines nehmen, auf das man sich aussucht, welche Oxide auf die Spitzen kommen.

Ich kann aber auch gerne eine separaten Test-Datensatz zusammen stellen, wenn das geeigneter wäre.

**Comment by MaraHochstein** [comment]
Ich hätte gerne einen "hübschen" Testdatensatz, der für alle zugänglich ist (d.h. ohne pwd-Beschränkung), mit ein paar anschaulichen Bildern (aber nicht gleich >200, sonst lädt es nur bei der Demo ewig) und ein paar Mineralen, die schon jetzt gut auf den verfügbaren Diagrammen dargestellt werden.

Wie man die Diagramme hinterher umstellt, würde ich davon erstmal unberücksichtigt lassen.

Das Testdataset epma-testdataset-02 war eigentlich ganz gut, hast Du davon noch die Dateien? Dort hatte ja auch nichts gefehlt / war falsch formatiert.

**Comment by MaraHochstein** [comment]
ich habe aktuell einfach eines der guf-records als "Demo" genommen, aber das hat keine Bilder und andere, die ich ausprobiert hatte, hatten so viele, dass ich nicht alle records testen wollte...

**Comment by Hezel2000** [comment]
OK, ich kümmere mich heute Abend darum.

**Comment by Hezel2000** [comment]
Ich hätte mal besser fragen sollen, bevor ich die Testdatensätze gelöscht habe, ich hatte wohl etwas zu viel Schwung. Auf der anderen Seite kann nun noch mal einen hoffentlich besonders anschaulichen machen.

**Comment by Hezel2000** [comment]
Ich habe eben 3 demo records angelegt, die findest Du in der Collection: GUF IfG EPMA Demo
