### ISSUE TITLE
references for standard condition writeup

### ISSUE THREAD

**Issue by MaraHochstein** [MaraHochstein/EPMAdatatools#9]
need references for standard condition writeup?

![grafik](https://github.com/MaraHochstein/EPMAdatatools/assets/117297458/259b99dc-f42b-4c96-a207-e807b642cc7b)

**Comment by Hezel2000** [comment]
Da nehmen wir mal diese hier, das ist eine Standard-Referenz:  
Pouchou, J.-L. & Pichoir, F. (1991): Quantitative analysis
of homogeneous or stratified microvolumes applying the
model “PAP”. In Electron Probe Quantification (K.F.J. Heinrich & D.E. Newbury, eds.). Plenum Press, New York,
N.Y. (31-75).
